apiVersion: v1
kind: Secret
metadata:
  name: fashion-secret
  namespace: fashion
  labels:
    app.kubernetes.io/part-of: fashion-ecommerce
type: Opaque
data:
  JWT_SECRET: Y2hhbmdlLW1lLWluLXByb2R1Y3Rpb24=
  DATABASE_PASSWORD: Y2hhbmdlLW1lLWluLXByb2R1Y3Rpb24=
  STRIPE_SECRET_KEY: Y2hhbmdlLW1lLWluLXByb2R1Y3Rpb24=
  SMTP_PASSWORD: Y2hhbmdlLW1lLWluLXByb2R1Y3Rpb24=
